---
bibliography: references.bib
---

# Pendahuluan

Suatu waktu mahasiswa calon pendidik matematika ditugaskan untuk mengembangkan sebuah simulasi digital sebagai media pembelajaran. Simulasi digital tersebut dimaksudkan untuk mengilustrasikan gerak parabola dari sebuah objek yang diluncurkan dengan kecepatan awal dan sudut elevasi tertentu, serta menggambarkan grafik ketinggian objek tersebut setiap waktunya. Menariknya, hampir semua produk simulasi mahasiswa tersebut, yaitu sekitar 96,7%, menggunakan persamaan matematis yang sama untuk merepresentasikan lintasan yang dilalui oleh objek tersebut dan relasi antara ketinggian objek tersebut setiap waktunya. Padahal, persamaan yang menggambarkan lintasan objek tersebut dan persamaan yang merepresentasikan ketinggian bola tersebut setiap waktunya menghubungkan kuantitas-kuantitas yang berbeda. Persamaan pertama menghubungkan jarak horizontal dan jarak vertikal (ketinggian) sedangkan persamaan kedua menghubungkan waktu dan ketinggian.

Ilustrasi tersebut paling tidak menunjukkan tiga hal. Pertama, masih banyak calon pendidik matematika yang kurang memiliki kepekaan terhadap seberapa realistik konteks yang dikembangkannya. Kedua, mahasiswa tersebut menganggap bahwa grafik dari relasi antara dua kuantitas sebagai gambar harfiah dari situasi yang diberikan [@hadjidemetriou2002]. Kekeliruan interpretasi grafik yang oleh @leinhardt1990 disebut sebagai kesulitan interpretasi ikonik ini mengindikasikan kurangnya pemahaman konseptual mahasiswa tentang grafik suatu relasi. Ketiga, mahasiswa tersebut masih menganggap matematika sebagai sebuah bidang ilmu yang terisolasi dari bidang-bidang ilmu lainnya. Ketika mereka menghadapi masalah gerak parabola, mereka hanya menyelesaikan masalah tersebut dengan menggunakan pengetahuan matematisnya. Sangat banyak dari mereka yang tidak menggunakan prinsip-prinsip fisika tentang gerak parabola untuk menyelesaikannya.

Ketiga masalah tersebut menggambarkan permasalahan besar dan nyata dalam upaya penyiapan para guru matematika masa depan yang juga ditemukan oleh penelitian-penelitian terdahulu. Dalam penelitiannya terhadap 32 mahasiswa calon pendidik matematika, @yilmaz2019 menemukan bahwa lebih dari setengah permasalahan yang dikembangkan oleh para calon pendidik matematika tersebut tidak cukup realistik. Temuan serupa juga ditemukan oleh banyak peneliti lainnya [misalnya, @bergsten2019; @jung2018; @paredes2020]. Terkait dengan pemahaman konseptual terhadap grafik, @billings2000 menemukan bahwa cukup banyak mahasiswa calon pendidik matematika yang mengalami kesulitan dalam mengkonstruksi dan menginterpretasi grafik, khususnya yang melibatkan kecepatan sebagai salah satu variabelnya. Hal ini senada dengan temuan @huang2012. Mereka menemukan bahwa masih banyak mahasiswa calon guru matematika dan sains yang kesulitan membuat keputusan dari grafik fungsi kecepatan terhadap waktu yang diberikan. Lebih jauh, penelitian-penelitian terdahulu juga menemukan bahwa masih cukup banyak mahasiswa calon pendidik matematika yang kesulitan dalam mengkoneksikan matematika dengan bidang ilmu lain atau permasalahan sehari-hari [@diana2020; @fajri2016; @prayitno2018].

Tiga masalah tersebut menjadi tantangan bagi para pendidik dan peneliti yang menyiapkan para guru matematika masa depan. @amte2017 menekankan bahwa para calon pendidik matematika perlu memiliki pemahaman esensial terhadap konsep-konsep dan praktik-praktik matematika. Praktik-praktik matematika tersebut termasuk kemampuan dalam menggunakan matematika untuk menyelesaikan permasalahan sehari-hari atau permasalahan dari bidang-bidang ilmu lain. Tak hanya itu, para calon pendidik matematika juga perlu dibekali kemampuan untuk mendesain aktivitas pembelajaran yang membuat peserta didik semangat belajar dan memahami kegunaan matematika bagi dirinya [@ainley2006].

Tantangan-tantangan tersebut dapat didekati dengan menggunakan apa yang disebut oleh @grossman2009 sebagai kerangka kerja "*teaching of practice*". Satu dari tiga konsep yang dikenalkan dalam kerangka kerja tersebut adalah *approximations of practice* atau pendekatan praktik. Berdasarkan ide ini, para mahasiswa calon pendidik matematika perlu mendapatkan kesempatan untuk terlibat dalam praktik-praktik mendasar dalam pengajaran matematika. Praktik seperti ini tidak hanya dapat membangun kecakapan matematis mahasiswa tetapi juga dapat membangun pengetahuan mereka tentang pengajaran [@álvarez2020]. Bagi mahasiswa tingkat awal, ide ini dapat dilakukan dengan memberikan pengalaman belajar bermakna bagi mereka melalui pembelajaran matematika yang efektif dan inovatif. Dengan cara seperti ini, mahasiswa akan membangun dan mengembangkan kecakapan matematisnya, serta dapat menganalisis praktik-praktik baik yang ditunjukkan dalam pengajaran seperti itu.

Karena tiga permasalahan utama yang dipaparkan sebelumnya menyangkut permasalahan realistik, pemahaman konseptual, dan koneksi matematika dengan bidang-bidang nonmatematika atau permasalahan sehari-hari, pendekatan pendidikan matematika realistik sesuai untuk digunakan dalam pembelajaran bagi para mahasiswa calon pendidik matematika. Melalui pengalaman belajar dalam perkuliahan yang menerapkan pendekatan ini, mereka akan dapat mengembangkan pemahaman konseptualnya tentang topik matematika yang diajarkan [@osana2011]. Selain itu, mereka juga akan terekspos dengan prinsip-prinsip desain pengajaran pendidikan matematika realistik, yaitu penemuan terbimbing, fenomenologi didaktis, dan pemodelan yang muncul [@gravemeijer2008].

Salah satu bagian terpenting dalam mendesain pembelajaran yang menerapkan pendidikan matematika realistik adalah pemilihan atau pengembangan permasalahan yang realistik. Permasalahan realistik tersebut tidak hanya digunakan sebagai motivasi tetapi juga sebagai landasan konseptual bagi mahasiswa untuk bermatematika. Selain itu, @ainley2006 menambahkan bahwa permasalahan tersebut juga perlu memberikan daya guna kepada mahasiswa. Untuk itu, permasalahan realistik yang berpotensi memotivasi mahasiswa, berdaya guna, dan dapat digunakan sebagai landasan konseptual bagi mereka untuk bermatematika diperlukan dalam mendesain pembelajaran dengan pendekatan pendidikan matematika realistik.

Menilik kajian pustaka yang dilakukan oleh @corner2015, secara umum anak muda lebih memiliki kesadaran terhadap perubahan iklim dibandingkan dengan kelompok umur yang lebih dewasa. Fakta ini menunjukkan potensi perubahan iklim untuk dijadikan konteks dalam pembelajaran matematika. Selain itu, penggunaan konteks ini juga dapat memberikan daya guna bagi mahasiswa calon pendidik matematika untuk mengetahui lebih jauh tentang fakta-fakta perubahan iklim.

Berdasarkan permasalahan dan peluang yang telah dipaparkan sebelumnya, tujuan makalah ini ada dua. Pertama, makalah ini akan mendeskripsikan desain pembelajaran yang menerapkan prinsip-prinsip desain pendidikan matematika realistik dan menggunakan konteks perubahan iklim. Kedua, makalah ini membahas bagaimana desain pembelajaran tersebut dapat membangun pemahaman konseptual mahasiswa calon pendidik matematika tentang grafik fungsi.
