# Penutup

Para calon pendidik matematika perlu terekspos terhadap pembelajaran matematika inovatif yang sesuai dengan kebutuhan zaman. Oleh karena itu, makalah ini telah memaparkan salah satu contoh desain pembelajaran matematika bagi para calon pendidik matematika agar mereka mendapatkan pengalaman belajar menyelesaikan masalah-masalah matematika yang realistik dan relevan, serta membangun pengetahuan-pengetahuan matematis berdasarkan masalah tersebut. Dengan cara seperti ini, mereka diharapkan memiliki visi tentang profil pendidik matematika yang profesional.

Desain pembelajaran matematika yang dipaparkan dalam makalah ini menggunakan tiga prinsip pendekatan pendidikan matematika realistik: penemuan terbimbing, fenomenologi didaktis, dan pemodelan yang muncul. Aktivitas-aktivitas pembelajaran dalam desain pembelajaran tersebut membimbing mahasiswa untuk melakukan matematisasi horizontal dan vertikal dalam membangun pengetahuan tentang transformasi fungsi. Proses matematisasi tersebut didukung dengan penyediaan masalah yang memantik kebutuhan intelektual mahasiswa akan gagasan-gagasan matematis dalam topik tersebut, serta ditunjang dengan teknologi matematika dinamis. Masalah yang digunakan adalah masalah perubahan iklim agar masalah tersebut juga memberikan wawasan tambahan bagi mahasiswa tentang isu-isu yang dihadapi oleh planet yang mereka tinggali. Dengan masalah tersebut, mereka berkesempatan memodelkan perubahan suhu permukaan bumi setiap tahunnya. Model tersebut dapat mereka gunakan untuk membangun pengetahuan tentang prinsip-prinsip transformasi fungsi.

Ilustrasi kasus Agatha dan Aurelia menunjukkan bahwa desain pembelajaran tersebut dapat membantu kedua mahasiswa tersebut membangun pengetahuan tentang transformasi fungsi, khususnya pergeseran vertikal grafik fungsi. Dengan menghadapi masalah pergantian garis dasar pengukuran suhu permukaan bumi, mereka memodelkan perubahan suhu permukaan bumi dan menggunakan model tersebut untuk membuat konjektur dan menemukan prinsip pergeseran vertikal grafik fungsi. Teknologi matematika dinamis yang disediakan membantu mereka dalam mengevaluasi konjektur mereka, mengkonstruksi prinsip pergeseran vertikal, dan menjustifikasinya.
