---
title: "Matematika Membumi: Ketika Matematika Realistik Bertemu dengan Permasalahan Planet Bumi dan Teknologi"
author:
- name: Yosep Dwi Kristanto
  url: https://people.usd.ac.id/~ydkristanto/
  affiliation: Pendidikan Matematika, Universitas Sanata Dharma
date: 2023/12/27
keywords: 
- pendidikan matematika realistik, realistic mathematics education, tujuan pembangunan berkelanjutan, sustainable development goals, perubahan iklim, climate change, pemanasan global, global warming, teknologi, Desmos
format:
  docx:
    reference-doc: custom-reference-doc.docx
    number-sections: true
    link-citations: true
  pdf:
    number-sections: true
    papersize: a4
    geometry: 
      - top = 25mm
      - left = 25mm
      - bottom = 25mm
      - right = 25mm
    mainfont: Times New Roman
    sansfont: Times New Roman
    monofont: Times New Roman
    fontsize: 12pt
    link-citations: true
editor: visual
bibliography: references.bib
csl: apa.csl
crossref: 
  tbl-title: Tabel
  tbl-prefix: Tabel
  fig-title: Gambar
  fig-prefix: Gambar
  sec-prefix: Bagian
  eq-title: Persamaan
  eq-prefix: Persamaan
---

```{r}
#| label: pendahuluan
#| child: "01-pendahuluan.qmd"
```

```{r}
#| label: isi
#| child: "02-isi.qmd"
```

```{r}
#| label: penutup
#| child: "03-penutup.qmd"
```

```{r}
#| label: ucapan-terima-kasih
#| child: "04-ucapan-terima-kasih.qmd"
```

```{r}
#| label: lampiran
#| child: "05-lampiran.qmd"
```

# Daftar Pustaka

::: {#refs}
:::

```{r}
#| label: biodata-penulis
#| child: "06-biodata-penulis.qmd"
```
